# fly.toml app configuration file generated for jrowah on 2024-09-14T15:50:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jrowah'
primary_region = 'cdg'
kill_signal = 'SIGTERM'

[build]

[env]
PHX_HOST = "jrowah.fly.dev"
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[http_services.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/health"
timeot = "5s"

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
